discogs_consumer_key: 
discogs_consumer_secret: 
discogs_request_token_url: 
discogs_authorize_url: 
discogs_access_token_url: 
discogs_app_name: 
discogs_user_token: 
artsy_client_id: 
artsy_client_secret: 
artsy_app_name:
artsy_token:
gracenote_client_id: 
gracenote_app_name: 
gracenote_user_id: 
s3_access_key_id: 
s3_secret_access_key: 
s3_bucket_name: 
s3_bucket_region: 